apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: l8pc0d938-go
  janus-idp.io/tekton: l8pc0d938-go
  backstage.io/kubernetes-id: l8pc0d938-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l8pc0d938-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
